version: "3.7"

services:
  api:
    build: ./api
    container_name: sd2
    restart: always
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      

